### ISSUE TITLE
[Bug]: Intermittent issue with emails not being sent

### ISSUE THREAD

**Issue by Smalls1652** [Smalls1652/SmallsOnline.PasswordExpirationNotifier#196]
There's a weird issue that started occurring within the past month or two where some people aren't receiving emails when they're scheduled to. It's not happening to all, just some.

I added an explicit error log when it happens (In #194) and that's showing me that a `404` response is being returned from the Graph API.

I just added in returning a custom exception for failed Graph API calls (In #195) to hopefully capture more data to see what's happening.

**Comment by Smalls1652** [comment]
Looks like this is the culprit:

```
SmallsOnline.PasswordExpirationNotifier.Lib.GraphApiException: The specified object was not found in the store., The process failed to get the correct properties.
```

Full inner stack trace:

```
SmallsOnline.PasswordExpirationNotifier.Lib.GraphApiException: The specified object was not found in the store., The process failed to get the correct properties.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at SmallsOnline.PasswordExpirationNotifier.Lib.Services.GraphClientService.SendApiCallAsync(String endpoint, HttpMethod httpMethod, String body) in /home/runner/work/SmallsOnline.PasswordExpirationNotifier/SmallsOnline.PasswordExpirationNotifier/src/Lib/Services/GraphClientService/general/SendApiCallAsync.cs:line 61
```
